development:
  dialect: mysql
  datasource: PiOwrb3U68:jg5xygPrLx@tcp(remotemysql.com:3306)/PiOwrb3U68
  dir: migrations

test:
  dialect: mysql
  datasource: PiOwrb3U68:jg5xygPrLx@tcp(remotemysql.com:3306)/PiOwrb3U68
  dir: migrations