development:
  dialect: postgres
  datasource: postgres://postgres:postgres@103.86.49.57:5432/practice?sslmode=disable
  dir: migrations
  table: migrations 

  # dialect: mysql
  # datasource: PiOwrb3U68:jg5xygPrLx@tcp(remotemysql.com:3306)/PiOwrb3U68?parseTime=true
  # dir: migrations
test:
  dialect: mysql
  datasource: root:pass@tcp(localhost:3306)/report
  dir: migrations
