
-- +migrate Up
CREATE TABLE IF NOT EXISTS bookings (
    id              INTEGER                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code    VARCHAR(255)       UNIQUE NOT NULL,
    description     VARCHAR(255)       NOT NULL,
    first_date      TIMESTAMP           NOT NULL,
    last_date       TIMESTAMP           NOT NULL,
    sign_id         INTEGER             ,CONSTRAINT FK_Sign_ID FOREIGN KEY (sign_id) REFERENCES Signs(id),
    applicant_id    VARCHAR(36)        ,CONSTRAINT FK_Applicant_ID FOREIGN KEY (applicant_id) REFERENCES Users(id),
    status          VARCHAR(255)       NOT NULL,
    comment         VARCHAR(255)       NOT NULL,
    created_at       TIMESTAMP           NOT NULL,
    updated_at       TIMESTAMP           NOT NULL,
    PRIMARY KEY (id)
);
-- +migrate Down
DROP TABLE bookings;